name: Deploy Redirect Site
on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [trigger-build]
permissions:
  contents: write
  pages: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Prepare redirect files
        run: |
          # Create a simple site structure for GitHub Pages
          mkdir -p docs
          cp index.html docs/
          cp 404.html docs/
          cp config.json docs/
          cp CNAME docs/
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
